<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>
	<version>3.21.0-SNAPSHOT</version>
	<groupId>eu.jsparrow</groupId>
	<artifactId>jsparrow-maven-plugin</artifactId>
	<packaging>maven-plugin</packaging>
	<description>Run jSparrow on Maven projects. See https://jsparrow.io/ for more information.</description>
	<name>jSparrow Maven Plugin</name>
	<url>https://jsparrow.io/</url>

	<properties>
		<java.version>11</java.version>
		<maven.version>3.6.0</maven.version>
		<maven.compiler.source>${java.version}</maven.compiler.source>
		<maven.compiler.target>${java.version}</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<proguard.plugin.version>2.4.0</proguard.plugin.version>
		<proguard.base.version>6.2.2</proguard.base.version>
		<nexus.base.url.reository>http://172.16.0.6:8082/nexus/content/repositories/</nexus.base.url.reository>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.apache.maven.plugin-testing</groupId>
			<artifactId>maven-plugin-testing-harness</artifactId>
			<version>3.3.0</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-compat</artifactId>
			<version>3.6.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-core</artifactId>
			<version>${maven.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-model</artifactId>
			<version>${maven.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-aether-provider</artifactId>
			<version>3.3.9</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-plugin-api</artifactId>
			<version>${maven.version}</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13</version>
			<type>jar</type>
			<scope>test</scope>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.mockito/mockito-core -->
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>2.23.4</version>
			<scope>test</scope>
		</dependency>


		<!-- https://mvnrepository.com/artifact/org.hamcrest/hamcrest-all -->
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-all</artifactId>
			<version>1.3</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-artifact</artifactId>
			<version>${maven.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-project</artifactId>
			<version>2.2.1</version>
		</dependency>

		<!-- dependencies to annotations -->
		<dependency>
			<groupId>org.apache.maven.plugin-tools</groupId>
			<artifactId>maven-plugin-annotations</artifactId>
			<version>${maven.version}</version>
			<scope>provided</scope>
		</dependency>

 		<dependency>
			<groupId>org.eclipse.platform</groupId>
			<artifactId>org.eclipse.osgi</artifactId>
			<version>3.17.200</version>
		</dependency>

		<dependency>
			<groupId>org.apache.maven.shared</groupId>
			<artifactId>maven-invoker</artifactId>
			<version>3.1.0</version>
			<!-- <version>3.0.0</version> -->
		</dependency>

		<!-- https://mvnrepository.com/artifact/com.google.guava/guava -->
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>23.0</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.twdata.maven/mojo-executor -->
		<dependency>
			<groupId>org.twdata.maven</groupId>
			<artifactId>mojo-executor</artifactId>
			<version>2.3.0</version>
		</dependency>

		<!-- https://mvnrepository.com/artifact/org.codehaus.plexus/plexus-utils -->
		<dependency>
			<groupId>org.codehaus.plexus</groupId>
			<artifactId>plexus-utils</artifactId>
			<version>3.1.1</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.apache.maven.shared/maven-verifier -->
		<dependency>
			<groupId>org.apache.maven.shared</groupId>
			<artifactId>maven-verifier</artifactId>
			<version>1.6</version>
		</dependency>

	</dependencies>

	<build>

		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>com.github.wvengen</groupId>
					<artifactId>proguard-maven-plugin</artifactId>
					<version>${proguard.plugin.version}</version>
					<executions>
						<execution>
							<phase>package</phase>
							<goals>
								<goal>proguard</goal>
							</goals>
						</execution>
					</executions>
					<dependencies>
						<!-- used maven obfuscation library -->
						<dependency>
							<groupId>net.sf.proguard</groupId>
							<artifactId>proguard-base</artifactId>
							<version>${proguard.base.version}</version>
							<scope>runtime</scope>
						</dependency>
					</dependencies>
					<configuration>
						<obfuscate>true</obfuscate>
						<!-- defines a proguard configuration that is loaded addition to the
							options and libs definition in the pom -->
						<proguardInclude>${basedir}/proguard.conf</proguardInclude>
						<addMavenDescriptor>true</addMavenDescriptor>
						<libs>
							<lib>${java.home}/lib/jrt-fs.jar</lib>
							<lib>${java.home}/jmods/java.base.jmod</lib>
							<lib>${java.home}/jmods/java.xml.jmod</lib> 
						</libs>
						<options>
							<!-- Default parameters -->
							<option>
								-useuniqueclassmembernames
							</option>
							<!-- Otherwise everything that is not used by an kept class would
								be thrown away -->
							<option>
								-dontshrink
								-dontoptimize
							</option>
							<!-- The SourceFile attribute is required, because Oracle/Sun's Java
								virtual machine otherwise does not include line numbers in stack traces,
								which is what you really want -->
							<!-- https://stackoverflow.com/a/6740226 -->
							<option>
								-renamesourcefileattribute SourceFile
							</option>
							<option>
								-adaptresourcefilecontents **.xml
							</option>
						</options>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>

		<resources>
			<resource>
				<directory>src/main/java</directory>
				<includes>
					<include>**/*.properties</include>
				</includes>
			</resource>
			<resource>
				<directory>src/main/resources</directory>
			</resource>
		</resources>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-plugin-plugin</artifactId>
				<version>${maven.version}</version>
				<executions>
					<execution>
						<id>help-goal</id>
						<goals>
							<goal>helpmojo</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.0</version>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
					<debug>true</debug>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.1.1</version>
				<configuration>
					<archive>
						<manifestEntries>
							<Built-By>Splendit IT-Consulting GmbH</Built-By>
						</manifestEntries>
						<!-- We need the artifact version in MANIFEST.MF. See https://stackoverflow.com/a/2713013 -->
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
							<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
						</manifest>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.1</version>
				<configuration>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<profiles>

		<profile>
			<id>proguard</id>
			<activation>
				<property>
					<name>proguard</name>
				</property>
				<!-- <file> <exists>${basedir}/proguard.conf</exists> </file> -->
			</activation>
			<build>
				<plugins>
					<plugin>
						<groupId>com.github.wvengen</groupId>
						<artifactId>proguard-maven-plugin</artifactId>
					</plugin>
				</plugins>
			</build>
		</profile>

		<profile>
			<id>develop-test-noProguard</id>
			<distributionManagement>
				<repository>
					<id>nexus</id>
					<url>${nexus.base.url.reository}jmp-develop-test-noProguard</url>
				</repository>
			</distributionManagement>
		</profile>

		<profile>
			<id>master-test-noProguard</id>
			<distributionManagement>
				<repository>
					<id>nexus</id>
					<url>${nexus.base.url.reository}jmp-master-test-noProguard</url>
				</repository>
			</distributionManagement>
		</profile>

		<profile>
			<id>master-production-proguard</id>
			<distributionManagement>
				<repository>
					<id>nexus</id>
					<url>${nexus.base.url.reository}jmp-master-production-proguard</url>
				</repository>
			</distributionManagement>
		</profile>

		<profile>
			<id>releaseCandidate</id>
			<distributionManagement>
				<repository>
					<id>nexus</id>
					<url>${nexus.base.url.reository}jmp-release-candidate/</url>
				</repository>
			</distributionManagement>
		</profile>
	</profiles>

</project>
