# "description" property - description of the feature
description=Tool for automated code improvement for java sources. A more detailed description can be found at https://jsparrow.github.io/

# "copyright" property - text of the "Feature Update Copyright"
copyright=Copyright 2026 Splendit IT-Consulting GmbH and Co KG

# "license" property - text of the "Feature Update License"
license=\
MIT License\n\
\n\
Permission is hereby granted, free of charge, to any person obtaining a copy\n\
of this software and associated documentation files (the “Software”), to deal\n\
in the Software without restriction, including without limitation the rights to\n\
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies \n\
of the Software, and to permit persons to whom the Software is furnished to do so, \n\
subject to the following conditions:\n\
\n\
The above copyright notice and this permission notice shall be included in all \n\
copies or substantial portions of the Software.\n\
\n\
THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR \n\
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, \n\
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\n\
\n\
---\n\
\n\
Commons Clause Restriction\n\
\n\
The Software is provided to you by the Licensor under the License, as defined above, subject to the following condition.\n\
\n\
Without limiting other conditions in the License, the grant of rights under the License will not include, and the License does not grant to you, the right to Sell the Software.\n\
\n\
For purposes of the foregoing, “Sell” means practicing any or all of the rights granted to you under the License to provide to third parties, for a fee or other consideration (including without limitation fees for hosting or consulting/support services related to the Software), a product or service whose value derives, entirely or substantially, from the functionality of the Software. Any license notice or attribution required by the License must also include this Commons Clause License Condition notice.\n\
\n\
License: MIT  \n\
Licensor: Splendit IT-Consulting GmbH\n\
---\n\
\n\
This product also includes libraries which are covered by the following licenses:\n\
\t- Eclipse Distribution License Version 1.0 (available at http://www.eclipse.org/licenses/edl-v1.0.html)\n\
\t- Common Public License Version 1.0 (available at http://www.eclipse.org/legal/cpl-v10.html)\n\
\t- Apache Software License 1.1 (available at http://www.apache.org/licenses/LICENSE)\n\
\t- Apache Software License 2.0 (available at http://www.apache.org/licenses/LICENSE-2.0)\n\
\t- Common Development and Distribution License (CDDL)Version 1.1 (available at http://glassfish.java.net/public/CDDL+GPL_1_1.html)
 ##### end of license property #####
