<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>at.splendit</groupId>
		<artifactId>eu.jsparrow</artifactId>
		<version>4.20.0-SNAPSHOT</version>
	</parent>

	<artifactId>features</artifactId>
	<packaging>pom</packaging>
	<name>jSparrow :: features</name>
	<description>jSparrow OSGi feature container</description>

	<modules>
		<!-- OSGi feature + site deployment -->
		<module>feature.3rd.party</module>

		<!-- standalone -->
		<module>feature.standalone</module>

		<!-- eclipse plugin at least Photon -->
		<module>feature.photon</module>

		<!-- eclipse plugin at least Photon -->
		<module>feature.202106</module>
	</modules>

</project>
